/* ════════════════════════════════════════════════
   Friend groups — bilingual strings, local to the lane (English
   reference, Urdu draft pending native review). A future pass merges
   these into the central locales under a groups.* namespace.

   Resolve: const { lang } = useI18n(); const s = STRINGS[lang] || STRINGS.en;
   ════════════════════════════════════════════════ */

export const STRINGS = {
  en: {
    list: {
      title: "Groups",
      intro: "Small circles of friends — a place to share and plan together.",
      empty: "No groups yet. Start one and invite the people you'd like along.",
      // For roles that can't create: a door, not an instruction they can't follow.
      emptyOther: (icon) =>
        `No groups yet. Groups are started by ${icon}s — when a friend starts one, your invitation will appear right here.`,
      startIconOnly: (icon) => `Groups are started by ${icon}s; joining is by invitation.`,
      createCta: "Start a group",
      invitesLabel: "Invitations",
      inviteLine: (inviter, group) => `${inviter} invited you to ${group}.`,
      accept: "Join",
      decline: "No thanks",
      creatorBadge: "You started this",
      openCta: "Open",
      loadError: "That didn't load. Please try again in a moment.",
    },
    create: {
      title: "Start a group",
      intro: "Give it a name, and a line about what it's for if you like. You can invite people once it's made.",
      nameLabel: "Group name",
      namePh: "For example: Tuesday Walkers",
      descLabel: "What's it about? (optional)",
      descPh: "A short line — where you meet, what you do…",
      createCta: "Create the group",
      creating: "Creating…",
      createdToast: "Group created ✓",
      cancel: "Cancel",
      errName: "Please give the group a name.",
      errGeneric: "That didn't work just now. Please try again.",
    },
    group: {
      back: "Back to groups",
      tabs: { feed: "Feed", chat: "Chat", members: "Members" },
      composerPh: "Share something with the group…",
      post: "Share",
      posting: "Sharing…",
      feedEmpty: "Nothing shared yet. Say the first hello.",
      chatPh: "Write a message…",
      send: "Send",
      chatEmpty: "No messages yet.",
      stickers: "Send a sticker",
      membersLabel: "Members",
      you: "you",
      creatorTag: "started the group",
      remove: "Remove",
      removeLabel: (name) => `Remove ${name} from the group`,
      leave: "Leave group",
      invite: "Invite someone",
      inviteTitle: "Invite a friend",
      inviteHint: "From your circle and your community friends. Tap a name to send an invitation.",
      noConnections: "No one to invite yet — add people to your circle or make friends in the community first.",
      invited: (name) => `Invited ${name}.`,
      inviteError: "That invitation couldn't be sent.",
      reportGroup: "Report this group",
      reportPost: "Report",
      reportReasonPh: "Tell us briefly what's wrong (optional)",
      reportSend: "Send report",
      reported: "Thank you. Our team will take a look.",
      actionError: "That didn't go through. Please try again.",
      hiddenNote: "Hidden by Saathban.",
      loadError: "That didn't load. Please try again in a moment.",
    },
  },

  ur: {
    // ⚠ Urdu draft — pending native review.
    list: {
      title: "گروپ",
      intro: "دوستوں کے چھوٹے حلقے — مل کر بانٹنے اور منصوبہ بنانے کی جگہ۔",
      empty: "ابھی کوئی گروپ نہیں۔ ایک شروع کریں اور اپنے پسندیدہ لوگوں کو بلائیں۔",
      emptyOther: (icon) =>
        `ابھی کوئی گروپ نہیں۔ گروپ ${icon} شروع کرتے ہیں — جب کوئی دوست شروع کرے گا، آپ کی دعوت یہیں نظر آئے گی۔`,
      startIconOnly: (icon) => `گروپ ${icon} شروع کرتے ہیں؛ شمولیت دعوت سے ہوتی ہے۔`,
      createCta: "گروپ شروع کریں",
      invitesLabel: "دعوتیں",
      inviteLine: (inviter, group) => `${inviter} نے آپ کو ${group} میں بلایا ہے۔`,
      accept: "شامل ہوں",
      decline: "نہیں شکریہ",
      creatorBadge: "یہ آپ نے شروع کیا",
      openCta: "کھولیں",
      loadError: "یہ نہیں کھل سکا۔ تھوڑی دیر میں دوبارہ کوشش کریں۔",
    },
    create: {
      title: "گروپ شروع کریں",
      intro: "اسے نام دیں، اور چاہیں تو ایک سطر کہ یہ کس لیے ہے۔ بننے کے بعد لوگوں کو بلا سکتے ہیں۔",
      nameLabel: "گروپ کا نام",
      namePh: "مثلاً: منگل کے سیر والے",
      descLabel: "یہ کس بارے میں ہے؟ (اختیاری)",
      descPh: "ایک مختصر سطر — کہاں ملتے ہیں، کیا کرتے ہیں…",
      createCta: "گروپ بنائیں",
      creating: "بن رہا ہے…",
      createdToast: "گروپ بن گیا ✓",
      cancel: "منسوخ",
      errName: "براہِ کرم گروپ کو نام دیں۔",
      errGeneric: "ابھی نہیں ہو سکا۔ براہِ کرم دوبارہ کوشش کریں۔",
    },
    group: {
      back: "واپس گروپوں کی طرف",
      tabs: { feed: "فیڈ", chat: "گفتگو", members: "اراکین" },
      composerPh: "گروپ کے ساتھ کچھ بانٹیں…",
      post: "بانٹیں",
      posting: "بانٹا جا رہا ہے…",
      feedEmpty: "ابھی کچھ نہیں بانٹا گیا۔ پہلا سلام آپ کریں۔",
      chatPh: "پیغام لکھیں…",
      send: "بھیجیں",
      chatEmpty: "ابھی کوئی پیغام نہیں۔",
      stickers: "اسٹیکر بھیجیں",
      membersLabel: "اراکین",
      you: "آپ",
      creatorTag: "نے گروپ شروع کیا",
      remove: "ہٹائیں",
      removeLabel: (name) => `${name} کو گروپ سے ہٹائیں`,
      leave: "گروپ چھوڑ دیں",
      invite: "کسی کو بلائیں",
      inviteTitle: "کسی دوست کو بلائیں",
      inviteHint: "اپنے حلقے اور برادری کے دوستوں میں سے۔ نام پر ٹیپ کر کے دعوت بھیجیں۔",
      noConnections: "ابھی بلانے کو کوئی نہیں — پہلے اپنے حلقے میں لوگ شامل کریں یا برادری میں دوست بنائیں۔",
      invited: (name) => `${name} کو دعوت بھیج دی۔`,
      inviteError: "یہ دعوت نہیں بھیجی جا سکی۔",
      reportGroup: "اس گروپ کی اطلاع دیں",
      reportPost: "اطلاع",
      reportReasonPh: "مختصراً بتائیں کیا غلط ہے (اختیاری)",
      reportSend: "اطلاع بھیجیں",
      reported: "شکریہ۔ ہماری ٹیم دیکھ لے گی۔",
      actionError: "یہ نہیں ہو سکا۔ براہِ کرم دوبارہ کوشش کریں۔",
      hiddenNote: "ساتھ بن نے چھپا دیا۔",
      loadError: "یہ نہیں کھل سکا۔ تھوڑی دیر میں دوبارہ کوشش کریں۔",
    },
  },
};
