/* ═══════════════════════════════════════════════════════════════
   0121 — a riddle helps one step at a time

   The owner: today's riddle gives too little help before a person gives
   up. Each riddle had ONE hint (hint_en / hint_ur, 0022), and one hint
   is a cliff: either it gives the thing away or it leaves the person
   exactly where they were.

   So each riddle now carries a short LADDER of hints, in both languages,
   revealed one at a time only when the person asks:
     1. a nudge — how to read the riddle, what kind of thing it is
     2. closer — where it lives, what it does
     3. nearly there — a plain description and the first letter, close
        enough that almost anyone gets there, without ever writing the
        answer itself

   STORED BESIDE THE RIDDLE, NOT BESIDE THE ANSWER. daily_puzzle_answers
   stays unreadable by every client; hints are read with the riddle under
   the existing "puzzles: community reads up to today" policy, so a
   future riddle's hints are no more visible than the riddle itself.

   ADDITIVE. hint_en / hint_ur are left exactly as they were, so a copy
   of the app that has not reloaded keeps showing its one hint. The
   ladder is authored content: a riddle added later gets its hints the
   same way, as rows here, and a riddle with no ladder falls back to its
   single hint in the app.

   Taking a hint changes nothing about the riddle's record: guesses are
   counted by guess_daily_puzzle and hints are never sent to the server.
   ═══════════════════════════════════════════════════════════════ */

alter table public.daily_puzzles
  add column if not exists hints_en text[],
  add column if not exists hints_ur text[];

alter table public.daily_puzzles
  drop constraint if exists daily_puzzles_hints_shape;
alter table public.daily_puzzles
  add constraint daily_puzzles_hints_shape check (
    (hints_en is null or cardinality(hints_en) between 1 and 5)
    and (hints_ur is null or cardinality(hints_ur) between 1 and 5)
  );

with ladder(d, h_en, h_ur) as (
  values
  ('2026-08-29'::date,
   array['Its hands move even when nobody touches them.',
         'It hangs on a wall or sits on a wrist, and it goes tick-tock.',
         'You look at it to know the time. It starts with C.'],
   array['اس کی سوئیاں کوئی چھوئے بغیر چلتی رہتی ہیں۔',
         'دیوار پر لٹکتی ہے یا کلائی پر بندھتی ہے، اور ٹک ٹک کرتی ہے۔',
         'وقت دیکھنا ہو تو اسی کو دیکھتے ہیں۔ پہلا حرف «گ» ہے۔']),
  ('2026-08-30',
   array['Think about what you reach for after washing your face.',
         'It hangs in the bathroom, soft and made of cloth.',
         'You dry yourself with it after a bath. It starts with T.'],
   array['منہ دھونے کے بعد کیا ہاتھ میں لیتے ہیں؟',
         'غسل خانے میں لٹکا رہتا ہے، نرم کپڑے کا۔',
         'نہانے کے بعد اسی سے جسم پونچھتے ہیں۔ پہلا حرف «ت» ہے۔']),
  ('2026-08-31',
   array['It is soft and squashy, and you squeeze it.',
         'It sits by the sink and helps wash the dishes.',
         'Soak it, squeeze it, and the water pours out. It starts with S.'],
   array['نرم سی چیز ہے، اسے دباتے ہیں۔',
         'برتن دھونے کی جگہ رکھی رہتی ہے۔',
         'بھگو کر دبائیں تو پانی نکل آتا ہے۔ پہلا حرف «ا» ہے۔']),
  ('2026-09-01',
   array['It has a neck and a mouth, but no face.',
         'It is usually made of glass or plastic.',
         'Water or milk goes inside, and a cap goes on top. It starts with B.'],
   array['گردن بھی ہے، منہ بھی، مگر چہرہ نہیں۔',
         'اکثر شیشے یا پلاسٹک کی ہوتی ہے۔',
         'اس میں پانی یا دودھ بھر کر ڈھکن لگاتے ہیں۔ پہلا حرف «ب» ہے۔']),
  ('2026-09-02',
   array['It is not something you can hold in your hand.',
         'Everybody has one, and it changes once a year.',
         'People ask "How old are you?" to find it out. Three letters, starting with A.'],
   array['یہ ہاتھ میں پکڑنے والی چیز نہیں۔',
         'ہر ایک کے پاس ہے، اور سال میں ایک بار بدلتی ہے۔',
         '«آپ کتنے سال کے ہیں؟» پوچھ کر جانی جاتی ہے۔ پہلا حرف «ع» ہے۔']),
  ('2026-09-03',
   array['Its teeth stand in one long, straight row.',
         'It is kept near the mirror.',
         'You run it through your hair in the morning. It starts with C.'],
   array['اس کے دانت ایک سیدھی قطار میں ہوتے ہیں۔',
         'آئینے کے پاس رکھی رہتی ہے۔',
         'صبح بالوں میں پھیری جاتی ہے۔ پہلا حرف «ک» ہے۔']),
  ('2026-09-04',
   array['Think of walking, not of carrying.',
         'You leave them behind on a sandy beach or a muddy path.',
         'Each one is made by a foot, one after another. It starts with F.'],
   array['اٹھانے کا نہیں، چلنے کا سوچیں۔',
         'ریت یا کیچڑ پر پیچھے رہ جاتے ہیں۔',
         'ہر ایک پاؤں سے بنتا ہے، ایک کے بعد ایک۔ پہلا حرف «ق» ہے۔']),
  ('2026-09-05',
   array['Every person is given one, from the day they are born.',
         'Other people say it when they want your attention.',
         'It is written on your letters and your ID card. Four letters, starting with N.'],
   array['ہر شخص کو پیدائش کے دن سے ملتا ہے۔',
         'دوسرے آپ کو بلانے کے لیے اسے پکارتے ہیں۔',
         'آپ کے خطوں اور شناختی کارڈ پر لکھا ہوتا ہے۔ پہلا حرف «ن» ہے۔']),
  ('2026-09-06',
   array['It is very thin, and its eye is a tiny hole.',
         'It lives in a sewing box.',
         'You pass thread through its eye to stitch cloth. It starts with N.'],
   array['بہت پتلی ہے، اور اس کی آنکھ ایک ننھا سا سوراخ ہے۔',
         'سلائی کے ڈبے میں رہتی ہے۔',
         'اس کی آنکھ میں دھاگہ ڈال کر کپڑا سیتے ہیں۔ پہلا حرف «س» ہے۔']),
  ('2026-09-07',
   array['You make it by taking something out, not by putting something in.',
         'A spade makes one in the ground.',
         'Keep digging into the earth and it gets deeper. Four letters, starting with H.'],
   array['یہ کچھ ڈالنے سے نہیں، نکالنے سے بنتا ہے۔',
         'بیلچہ زمین میں اسے بناتا ہے۔',
         'زمین کھودتے جائیں تو یہ گہرا ہوتا جاتا ہے۔ پہلا حرف «گ» ہے۔']),
  ('2026-09-08',
   array['It is about time, not about a person.',
         'When it finally comes, it has a different name.',
         'It is the day after today. It starts with T.'],
   array['یہ کسی شخص کا نہیں، وقت کا ذکر ہے۔',
         'جب آ جائے تو اس کا نام بدل جاتا ہے۔',
         'آج کے بعد والا دن۔ دو حرفوں کا لفظ ہے۔']),
  ('2026-09-09',
   array['You cannot see it or touch it.',
         'A library asks for it, and so does a prayer.',
         'It is what there is when nobody makes a sound. It starts with S.'],
   array['نہ دیکھی جا سکتی ہے، نہ چھوئی جا سکتی ہے۔',
         'کتب خانے میں اور دعا کے وقت اسی کی ضرورت ہوتی ہے۔',
         'جب کوئی آواز نہ ہو تو یہی ہوتی ہے۔ پہلا حرف «خ» ہے۔']),
  ('2026-09-10',
   array['Its "bed" and its "running" are both about water.',
         'It starts in the mountains and ends in the sea.',
         'The Ravi and the Indus are both one. It starts with R.'],
   array['اس کا «بستر» اور اس کا «دوڑنا» دونوں پانی کی باتیں ہیں۔',
         'پہاڑوں سے نکلتا ہے اور سمندر میں جا ملتا ہے۔',
         'راوی اور سندھ دونوں یہی ہیں۔ پہلا حرف «د» ہے۔']),
  ('2026-09-11',
   array['It goes in and out of you all day long.',
         'You hold it when you dip under water.',
         'In through the nose, out through the mouth. It starts with B.'],
   array['سارا دن آپ کے اندر آتا جاتا ہے۔',
         'پانی میں ڈبکی لگاتے وقت اسے روکتے ہیں۔',
         'ناک سے اندر، منہ سے باہر۔ پہلا حرف «س» ہے۔']),
  ('2026-09-12',
   array['It is something you eat.',
         'It is a big, round fruit that comes in hot weather.',
         'Heavy, green outside, red and juicy inside. Its name has the word "water" in it.'],
   array['یہ کھانے کی چیز ہے۔',
         'بڑا، گول پھل ہے جو گرمیوں میں آتا ہے۔',
         'باہر سے ہرا، اندر سے لال اور رسیلا۔ پہلا حرف «ت» ہے۔']),
  ('2026-09-13',
   array['It is small and flat, and it goes on paper.',
         'The post office sells it.',
         'You stick it in the corner of an envelope before posting a letter. It starts with S.'],
   array['چھوٹا اور چپٹا ہے، کاغذ پر لگتا ہے۔',
         'ڈاک خانے میں بکتا ہے۔',
         'خط بھیجنے سے پہلے لفافے کے کونے پر چپکاتے ہیں۔ پہلا حرف «ٹ» ہے۔']),
  ('2026-09-14',
   array['The "house" is a shell.',
         'A hen gives you one.',
         'You fry it or boil it for breakfast, and the golden treasure is the yolk. Three letters.'],
   array['«گھر» دراصل ایک چھلکا ہے۔',
         'مرغی دیتی ہے۔',
         'ناشتے میں تل کر یا ابال کر کھاتے ہیں، اور سنہری خزانہ اس کی زردی ہے۔ پہلا حرف «ا» ہے۔']),
  ('2026-09-15',
   array['It comes down from the sky.',
         'It is white and cold, and it covers the mountains.',
         'In winter it falls in soft flakes on Murree and Swat. Four letters, starting with S.'],
   array['آسمان سے اترتی ہے۔',
         'سفید اور ٹھنڈی، پہاڑوں کو ڈھانپ لیتی ہے۔',
         'سردیوں میں مری اور سوات پر نرم گالوں کی صورت گرتی ہے۔ پہلا حرف «ب» ہے۔']),
  ('2026-09-16',
   array['Its "tongue" is a flap of leather.',
         'You wear two of them at once.',
         'It has laces and goes on your foot. Four letters, starting with S.'],
   array['اس کی «زبان» چمڑے کا ایک ٹکڑا ہے۔',
         'ان کا جوڑا پہنا جاتا ہے۔',
         'اس میں تسمے ہوتے ہیں اور یہ پاؤں میں پہنا جاتا ہے۔ پہلا حرف «ج» ہے۔']),
  ('2026-09-17',
   array['The "field" is a page, and the "seeds" are letters.',
         'It has a cover and many pages.',
         'You open it and read it. Four letters, starting with B.'],
   array['«کھیت» صفحہ ہے، اور «بیج» حروف ہیں۔',
         'اس کی جلد ہوتی ہے اور بہت سے صفحے۔',
         'اسے کھول کر پڑھتے ہیں۔ پہلا حرف «ک» ہے۔']),
  ('2026-09-18',
   array['Its "crying" is rain.',
         'It floats high in the sky.',
         'White or grey, it brings the monsoon rain. It starts with C.'],
   array['اس کا «رونا» بارش ہے۔',
         'آسمان میں اونچا تیرتا ہے۔',
         'سفید یا سرمئی، ساون کی بارش لاتا ہے۔ پہلا حرف «ب» ہے۔']),
  ('2026-09-19',
   array['You catch it, but not with your hands.',
         'It is a small illness.',
         'A runny nose and sneezing mean you have one. It starts with C.'],
   array['اسے ہاتھوں سے نہیں پکڑتے۔',
         'ایک چھوٹی سی بیماری ہے۔',
         'بہتی ناک اور چھینکیں اس کی نشانی ہیں۔ پہلا حرف «ز» ہے۔']),
  ('2026-09-20',
   array['Think about a place where words are kept in order.',
         'It is a book that lists words from A to Z.',
         'You look in it to find what a word means. It starts with D.'],
   array['سوچیں الفاظ کہاں ترتیب سے رکھے جاتے ہیں۔',
         'ایسی کتاب جس میں الفاظ حروفِ تہجی کی ترتیب سے لکھے ہوں۔',
         'کسی لفظ کا مطلب ڈھونڈنا ہو تو اسی میں دیکھتے ہیں۔ پہلا حرف «ل» ہے۔']),
  ('2026-09-21',
   array['It stretches a very long way.',
         'Buses, cars and carts travel along it.',
         'Made of tar, it joins one town to the next. Four letters, starting with R.'],
   array['بہت دور تک پھیلی ہوتی ہے۔',
         'بسیں، گاڑیاں اور تانگے اس پر چلتے ہیں۔',
         'تارکول سے بنی، ایک شہر کو دوسرے سے ملاتی ہے۔ پہلا حرف «س» ہے۔']),
  ('2026-09-22',
   array['It is a fruit.',
         'You peel it before eating it, and it is curved.',
         'Long and yellow, and sold by the dozen. It starts with B.'],
   array['یہ ایک پھل ہے۔',
         'کھانے سے پہلے چھیلتے ہیں، اور یہ مڑا ہوا ہوتا ہے۔',
         'لمبا اور پیلا، اور درجن کے حساب سے بکتا ہے۔ پہلا حرف «ک» ہے۔']),
  ('2026-09-23',
   array['Someone on a rooftop holds the "string".',
         'The wind lifts it up.',
         'Made of paper and thin sticks, it is flown in spring. Four letters, starting with K.'],
   array['«ڈور» چھت پر کوئی تھامے ہوتا ہے۔',
         'ہوا اسے اوپر اٹھاتی ہے۔',
         'کاغذ اور پتلی تیلیوں سے بنتی ہے، بہار میں اڑائی جاتی ہے۔ پہلا حرف «پ» ہے۔']),
  ('2026-09-24',
   array['You use it with water.',
         'It gets your hands clean.',
         'A bar that gets smaller every time you wash. Four letters, starting with S.'],
   array['پانی کے ساتھ استعمال ہوتا ہے۔',
         'ہاتھ صاف کرتا ہے۔',
         'ایک ٹکیہ جو ہر دھلائی کے ساتھ چھوٹی ہوتی جاتی ہے۔ پہلا حرف «ص» ہے۔']),
  ('2026-09-25',
   array['You see it at night, not in the day.',
         'It changes its shape through the month.',
         'Round and bright, and everyone looks for the new one at Eid. Four letters, starting with M.'],
   array['رات کو نظر آتا ہے، دن کو نہیں۔',
         'مہینے بھر اپنی شکل بدلتا ہے۔',
         'گول اور روشن، عید پر نیا دیکھنے سب چھتوں پر جاتے ہیں۔ پہلا حرف «چ» ہے۔']),
  ('2026-09-26',
   array['The "head" and the "tail" are its two sides.',
         'It is small, round and made of metal.',
         'It is money you can toss to decide something. It starts with C.'],
   array['«سر» اور «دُم» اس کے دو رخ ہیں۔',
         'چھوٹا، گول اور دھات کا بنا ہوا۔',
         'یہ پیسہ ہے جسے اچھال کر فیصلہ کرتے ہیں۔ پہلا حرف «س» ہے۔']),
  ('2026-09-27',
   array['It does not climb by itself; something inside it rises.',
         'A doctor may put one under your tongue.',
         'It tells you how hot or cold it is. It starts with T.'],
   array['خود نہیں چڑھتا؛ اس کے اندر کچھ اوپر اٹھتا ہے۔',
         'ڈاکٹر اسے زبان کے نیچے رکھتے ہیں۔',
         'بتاتا ہے کہ کتنی گرمی یا سردی ہے۔ پہلا حرف «ت» ہے۔'])
)
update public.daily_puzzles p
set hints_en = l.h_en, hints_ur = l.h_ur
from ladder l
where p.puzzle_date = l.d;
